pie title HubXCoin ($HUBX) Tokenomics Distribution
    "Ecosystem Rewards (Proof of Workout)" : 40
    "Liquidity & Staking" : 20
    "Development & Treasury" : 15
    "Team & Advisors" : 10
    "Public Launch" : 10
    "Strategic Partners" : 5
